"use strict";

const map = {
  "cd-i": "cdi",
  "cps1": "cps-1",
  "cps2": "cps-2",
  "cps3": "cps-3",
  "commodore-64": "c64",
  "gb": "game-boy",
  "gba": "game-boy-advance",
  "gbc": "game-boy-color",
  "gamegear": "game-gear",
  "game-watch": "game-and-watch",
  "gnw": "game-and-watch",
  "mame": "arcade",
  "megacd": "mega-cd",
  "mega-drive": "megadrive",
  "model1": "model-1",
  "model2": "model-2",
  "model3": "model-3",
  "neogeo": "neo-geo",
  "neogeocd": "neo-geo-cd",
  "ngp": "neo-geo-pocket",
  "nintendo-ds": "ds",
  "n64": "nintendo-64",
  "pcengine": "pc-engine",
  "playstation2": "playstation-2",
  "sms": "master-system",
  "snes": "super-nes",
  "super-nintendo": "super-nes",
  "videopac": "odyssey-2",
  "windows-phone-7": "windows-phone",
};

module.exports = id => id in map ? map[id] : id;
